# Generated by Django 2.1 on 2018-08-24 07:37

from django.db import migrations, models
import snippet.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_snippet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='image',
            field=models.ImageField(default='snippet/default.jpg', upload_to=snippet.modelutils.PathAndRename('snippet/'), verbose_name='图片'),
        ),
    ]
