# Generated by Django 2.1 on 2018-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='intro',
            field=models.CharField(default='', max_length=256, verbose_name='简介'),
        ),
    ]
