# Generated by Django 2.1 on 2019-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_auto_20180824_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.CharField(
                default='', max_length=64, verbose_name='标签'),
            preserve_default=False,
        ),
    ]
