# Generated by Django 2.1 on 2019-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_snippet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标签'),
        ),
    ]
